# Generated by Django 4.2.6 on 2023-10-16 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='sex',
            field=models.CharField(max_length=200),
        ),
    ]
